---
- name: Instruqt alert
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print EDA event message
      debug:
        var: ansible_eda
      msg: "{{ ansible_date_time.iso8601 }} - {{ event.payload.type }}: {{ event.payload.track_slug}} {{ event.payload.participant_id }}"
